model_checkpoint:
  _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  dirpath: "checkpoints"
  monitor: epoch_metrics/val_loss
  mode: min
  filename: '${name}--{epoch}-{step}'
