neptune:
  _target_: pytorch_lightning.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_KEY}
  project: {{ cookiecutter.neptune_workspace }}/{{ cookiecutter.repo_name }}
  name: "${name}"
  log_model_checkpoints: false
  tags: "${tags}"
